# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
